import "~/styles/globals.css";

import { ClerkProvider } from '@clerk/nextjs';

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by Nuxehs",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex items-center justify-between border-b flex-wrap p-6 text-xl font-semibold"> 
    <div>T3 Gallery</div>

    <div>Sign In</div>
    </nav>
  );
}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={`font-sans ${GeistSans.variable} flex flex-col gap-4`}>
        <TopNav />
      {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
